### ISSUE TITLE
How to run this code !!

### ISSUE THREAD

**Issue by ORCA666** [FSecureLABS/Ninjasploit#5]
Hallo everyone, thank you for your attention, I am asking for the 1000 time, but yet politely cz I am a polite person, how to compile this code ! I am using vs 2019 (and then I used gcc) , first there is no common.h file, if I have to create it wht didn't you just say that, and second there is a bunch of unrecognized header files, third the most annoying part is that I really like the idea of this code but still i do not know how to use it ... so please anyone reading this and you did really compile it , or you have an idea that may help compiling this code let me know

**Comment by T35R6braPwgDJKq** [comment]
uhm, you know that this is a meterpreter plugin?
